import assert from 'node:assert/strict';
import { parseHTML } from 'linkedom';
import { iniciar } from '../src/controle';
const criar = (html: string) => parseHTML(`<html><body>${html}</body></html>`).document as unknown as Document;
const row = '<tr><td><a href="controlador.php?acao=anotacao_registrar&id_protocolo=1&infra_hash=abc" aria-label="Anotação: Primeiro">nota</a></td><td><a href="controlador.php?acao=procedimento_trabalhar&id_procedimento=1">123</a></td></tr>';
const esperar = () => new Promise(resolve => setTimeout(resolve, 100));
const d = criar(`<table id="tblProcessosRecebidos"><tbody>${row}</tbody></table>`);
let leituras = 0;
const c = iniciar({doc: d, lerPagina: async () => { leituras++; return criar('<input id="chkSinPrioridade" checked>'); }});
c.configurar(false); await esperar(); assert.equal(leituras, 0);
c.configurar(true); await esperar();
assert.equal(d.querySelectorAll('.spro-anotacao-prioridade').length, 1);
assert.equal(leituras, 1);
d.querySelector('tbody')!.insertAdjacentHTML('beforeend', row);
await esperar(); assert.equal(d.querySelectorAll('.spro-anotacao').length, 2); assert.equal(leituras, 1);
d.querySelector('a')!.setAttribute('aria-label', 'Anotação: Atualizado');
await esperar(); assert.match(d.querySelector('.spro-anotacao')!.textContent!, /Atualizado/);
c.configurar(false); await esperar(); assert.equal(d.querySelectorAll('.spro-anotacao').length, 0);
c.fechar();
console.log('OK: opção, prioridade, novas linhas, alteração e desligamento ao vivo');
const falha = criar(`<table id="tblProcessosGerados"><tbody>${row}</tbody></table>`);
let tentativas = 0;
const cf = iniciar({doc: falha, lerPagina: async () => { tentativas++; throw new Error('Sessão expirada'); }});
cf.configurar(true); await esperar();
assert.equal(falha.querySelectorAll('.spro-anotacao').length, 1);
assert.equal(tentativas, 1); cf.configurar(true); await esperar(); assert.equal(tentativas, 1); cf.fechar();
console.log('OK: falha de IO mantém texto e não repete requisições');
let resolver!: (doc: Document) => void;
const tardia = criar(`<table id="tblProcessosRecebidos"><tbody>${row}</tbody></table>`);
const ct = iniciar({doc: tardia, lerPagina: () => new Promise(resolve => { resolver = resolve; })});
ct.configurar(true); ct.configurar(false); resolver(criar('<input id="chkSinPrioridade" checked>')); await esperar();
assert.equal(tardia.querySelectorAll('.spro-anotacao').length, 0); ct.fechar();
console.log('OK: resposta tardia não reativa opção desligada');
const duplicada = criar(`<table id="tblProcessosRecebidos"><tbody>${row}${row}</tbody></table>`);
let repetidas = 0;
const cd = iniciar({doc: duplicada, lerPagina: async () => { repetidas++; return criar('<input id="chkSinPrioridade">'); }});
cd.configurar(true); await esperar(); assert.equal(repetidas, 1); cd.fechar();
console.log('OK: mesmo processo em duas linhas gera uma leitura de prioridade');
