import { resumo } from "./util";
import { verificarAbertura } from "./verificar-abertura";
import { verificarArmazenamento } from "./verificar-armazenamento";
import { verificarAviso } from "./verificar-aviso";
import { verificarCodec } from "./verificar-codec";
import { verificarCombobox, verificarComboboxNoDialogo } from "./verificar-combobox";
import { verificarDatas } from "./verificar-datas";
import { verificarEntidade } from "./verificar-entidade";
import { verificarFlutuante } from "./verificar-flutuante";
import { verificarId } from "./verificar-id";
import { verificarPonteLateralGenerica } from "./verificar-lateral";
import { verificarMenu } from "./verificar-menu";
import { verificarOpcoes } from "./verificar-opcoes";
import { verificarRpc } from "./verificar-rpc";
import { verificarUi } from "./verificar-ui";

verificarDatas();
verificarUi();
verificarAviso();
await verificarArmazenamento();
verificarEntidade();
await verificarOpcoes();
await verificarRpc();
verificarId();
verificarAbertura();
await verificarCodec();
await verificarCombobox();
await verificarComboboxNoDialogo();
await verificarMenu();
await verificarFlutuante();
await verificarPonteLateralGenerica();
resumo();
