import { resumo } from "./util";
import { verificarAbertura } from "./verificar-abertura";
import { verificarArmazenamento } from "./verificar-armazenamento";
import { verificarCodec } from "./verificar-codec";
import { verificarCombobox, verificarComboboxNoDialogo } from "./verificar-combobox";
import { verificarDatas } from "./verificar-datas";
import { verificarEntidade } from "./verificar-entidade";
import { verificarId } from "./verificar-id";
import { verificarMenu } from "./verificar-menu";
import { verificarOpcoes } from "./verificar-opcoes";
import { verificarRpc } from "./verificar-rpc";
import { verificarUi } from "./verificar-ui";

verificarDatas();
verificarUi();
await verificarArmazenamento();
verificarEntidade();
await verificarOpcoes();
await verificarRpc();
verificarId();
verificarAbertura();
await verificarCodec();
await verificarCombobox();
await verificarComboboxNoDialogo();
await verificarMenu();
resumo();
