import { verificarMotor } from "./verificar-motor";
import { verificarErro429, verificarProvedor, verificarRaciocinioComFerramentas } from "./verificar-provedor";
import { verificarSkills } from "./verificar-skills";
import { verificarMcp } from "./verificar-mcp";
import { verificarMcpPermissao, verificarMcpTools } from "./verificar-mcp-permissao";
import { verificarMcpUi } from "./verificar-mcp-ui";
import { verificarRotinasUi } from "./verificar-rotinas-ui";
import { verificarBackground } from "./verificar-background";
import { verificarConviteDeAvaliacao } from "./verificar-convite-avaliacao";
import { verificarEspelho, verificarEspelhoNosModulos, verificarEspelhoRevisao, verificarEspelhoSync } from "./verificar-espelho";
import { verificarOpcoesSync } from "./verificar-opcoes-sync";
import { verificarCartaoDeErro, verificarDiagnostico as verificarDiagnosticoDoErro } from "./verificar-diagnostico";
import { verificarCamposLivres, verificarEnvelope, verificarHtmlOculto, verificarInjecao, verificarPromptSeguranca } from "./verificar-injecao";
import { verificarDesfazer } from "./verificar-desfazer";
import { verificarRegras } from "./verificar-regras";
import { verificarCusto } from "./verificar-custo";
import { verificarRotinas } from "./verificar-rotinas";
import { verificarCambio, verificarSugestoes } from "./verificar-sugestoes";
import { verificarFluxosModelo, verificarFluxosRevisao } from "./verificar-fluxos";
import { verificarAvaliarFluxo, verificarDiagnostico, verificarProcessoDaArvore } from "./verificar-avaliar";
import { verificarInferirFluxo } from "./verificar-inferir";
import { verificarEstudio, verificarHistoricoDoModelo, verificarMetadadosDoModelo, verificarTextoDoDiagnostico } from "./verificar-estudio";
import { verificarCartaoDaCapa, verificarCartaoDeFluxo } from "./verificar-cartao";
import { verificarDom } from "./verificar-dom";
import { verificarPonte } from "./verificar-ponte";
import { verificarOpFluxoAvaliar } from "./verificar-op-fluxo";
import { verificarDepoisDaEscrita } from "./verificar-depois-escrita";
import { verificarEstilosDoEditor } from "./verificar-estilos";
import { verificarSimilares } from "./verificar-similares";
import { verificarFluxoMarkdown } from "./verificar-fluxo-md";
import { verificarColecaoDeFluxos } from "./verificar-colecao-fluxos";
import { verificarEditarConteudo } from "./verificar-editar-conteudo";
import { verificarFaixaDeFluxo } from "./verificar-faixa";
import { verificarFavoritosTool } from "./verificar-favoritos-tool";
import { verificarHistoricoTool } from "./verificar-historico-tool";
import { resumo } from "./util";

await verificarMotor();
await verificarFavoritosTool();
await verificarHistoricoTool();
await verificarProvedor();
await verificarErro429();
await verificarRaciocinioComFerramentas();
await verificarSkills();
await verificarMcp();
verificarMcpPermissao();
await verificarMcpTools();
await verificarMcpUi();
verificarDesfazer();
verificarRegras();
verificarCusto();
verificarRotinas();
await verificarRotinasUi();
await verificarBackground();
verificarConviteDeAvaliacao();
verificarEspelho();
await verificarEspelhoSync();
await verificarEspelhoNosModulos();
await verificarEspelhoRevisao();
verificarOpcoesSync();
verificarDiagnosticoDoErro();
await verificarCartaoDeErro();
verificarInjecao();
verificarEnvelope();
verificarHtmlOculto();
verificarPromptSeguranca();
verificarCamposLivres();
verificarSugestoes();
verificarCambio();
verificarFluxosModelo();
verificarFluxosRevisao();
verificarAvaliarFluxo();
verificarProcessoDaArvore();
verificarDiagnostico();
await verificarInferirFluxo();
verificarEstudio();
verificarMetadadosDoModelo();
verificarHistoricoDoModelo();
verificarTextoDoDiagnostico();
verificarCartaoDeFluxo();
verificarCartaoDaCapa();
verificarDom();
verificarPonte();
await verificarOpFluxoAvaliar();
verificarDepoisDaEscrita();
verificarEstilosDoEditor();
verificarSimilares();
await verificarFluxoMarkdown();
verificarColecaoDeFluxos();
await verificarEditarConteudo();
verificarFaixaDeFluxo();
resumo();
