import { resumo } from "./util";
import { verificarApp } from "./verificar-app";
import { verificarAtualizar } from "./verificar-atualizar";
import { verificarBalao } from "./verificar-balao";
import { verificarBotao } from "./verificar-botao";
import { verificarCaptura } from "./verificar-captura";
import { verificarControleSync } from "./verificar-controle-sync";
import { verificarControleArquivo, verificarCopias } from "./verificar-copias";
import { verificarDialogos } from "./verificar-dialogos";
import { verificarDocumentosFavoritos } from "./verificar-docfav";
import { verificarDocumentos } from "./verificar-documentos";
import { verificarEnviar } from "./verificar-enviar";
import { verificarExibicao } from "./verificar-exibicao";
import { verificarLateralAba, verificarLateralApp } from "./verificar-lateral";
import { verificarLegado } from "./verificar-legado";
import { verificarLista } from "./verificar-lista";
import { verificarMapa } from "./verificar-mapa";
import { verificarMigracao } from "./verificar-migracao";
import { verificarModelo } from "./verificar-modelo";
import { verificarMotor } from "./verificar-motor";
import { verificarContador, verificarNovidades } from "./verificar-novidades";
import { verificarOpcoes } from "./verificar-opcoes";
import { verificarPagina } from "./verificar-pagina";
import { verificarPainel } from "./verificar-painel";
import { verificarPrazo } from "./verificar-prazo";
import { verificarRepositorio } from "./verificar-repositorio";
import { verificarShell } from "./verificar-shell";
import { verificarSincroniaTexto } from "./verificar-sincronia";

verificarModelo();
verificarPrazo();
await verificarRepositorio();
verificarMigracao();
await verificarPagina();
await verificarBalao();
await verificarPainel();
verificarLista();
await verificarDialogos();
await verificarApp();
verificarLegado();
verificarExibicao();
await verificarLateralAba();
await verificarLateralApp();
await verificarShell();
await verificarBotao();
await verificarOpcoes();
await verificarEnviar();
await verificarMapa();
await verificarDocumentos();
await verificarSincroniaTexto();
await verificarMotor();
await verificarControleSync();
await verificarCopias();
await verificarControleArquivo();
await verificarNovidades();
await verificarContador();
await verificarDocumentosFavoritos();
await verificarCaptura();
await verificarAtualizar();
resumo();
