import { resumo } from "./util";
import { verificarApp } from "./verificar-app";
import { verificarBalao } from "./verificar-balao";
import { verificarBotao } from "./verificar-botao";
import { verificarDialogos } from "./verificar-dialogos";
import { verificarEnviar } from "./verificar-enviar";
import { verificarExibicao } from "./verificar-exibicao";
import { verificarLateralAba, verificarLateralApp } from "./verificar-lateral";
import { verificarLegado } from "./verificar-legado";
import { verificarLista } from "./verificar-lista";
import { verificarMapa } from "./verificar-mapa";
import { verificarMigracao } from "./verificar-migracao";
import { verificarModelo } from "./verificar-modelo";
import { verificarOpcoes } from "./verificar-opcoes";
import { verificarPagina } from "./verificar-pagina";
import { verificarPainel } from "./verificar-painel";
import { verificarPrazo } from "./verificar-prazo";
import { verificarRepositorio } from "./verificar-repositorio";
import { verificarShell } from "./verificar-shell";

verificarModelo();
verificarPrazo();
await verificarRepositorio();
verificarMigracao();
await verificarPagina();
await verificarBalao();
await verificarPainel();
verificarLista();
await verificarDialogos();
await verificarApp();
verificarLegado();
verificarExibicao();
await verificarLateralAba();
await verificarLateralApp();
await verificarShell();
await verificarBotao();
await verificarOpcoes();
await verificarEnviar();
await verificarMapa();
resumo();
